version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: wordle-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - wordle_data:/app/data
      - ./backend:/app  # Mount source code for hot reload
    environment:
      - DATABASE_PATH=/app/data/wordle_stats.db
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["python", "-u", "main.py"]  # Unbuffered output

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wordle-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  wordle_data:
    driver: local

networks:
  default:
    name: wordle-network-dev
